version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak:8.0.1
    environment:
      - DB_ADDR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8081:8080
